server:
  port: 8000
spring:
  application:
    name: "inventory"
  datasource:
    url: jdbc:postgresql://localhost:4040/inventory
    username: app
    password: app
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
