version: "3.7"
services:
  inventory_db:
    container_name: inventory-db
    image: postgres:16-alpine
    restart: always
    shm_size: 256mb
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_PASSWORD=app
      - POSTGRES_USER=app
      - POSTGRES_DB=inventory
    volumes:
      - app_data:/var/lib/postgresql/data

volumes:
  app_data:
